# Generated by Django 2.0 on 2020-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200218_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
